services:
  next-app:
    container_name: chat-mate-nextjs-app
    build:
      context: ./

    environment:
      - QDRANT_URL=http://qdrant:6333/

    env_file:
      - .env
    # volumes:
    #   - ./src:/app/src
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        # target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - my_network

configs:
  qdrant_config:
    content: |
      log_level: INFO      

networks:
  my_network:
    external: true